### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGlobalFunctions' of null

### ISSUE THREAD

**Issue by hahmjt** [Gert-dev/php-integrator-autocomplete-plus#12]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.1
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'getGlobalFunctions' of null

```
At /Users/hahmjt/.atom/packages/php-integrator-autocomplete-plus/lib/FunctionProvider.coffee:26

TypeError: Cannot read property 'getGlobalFunctions' of null
    at FunctionProvider.module.exports.FunctionProvider.getSuggestions (/Users/hahmjt/.atom/packages/php-integrator-autocomplete-plus/lib/FunctionProvider.coffee:26:24)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  5x -0:10.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:10 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:10 snippets:expand (atom-text-editor.editor.is-focused)
     -0:10 editor:indent (atom-text-editor.editor.is-focused)
     -0:09.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:05.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:03.7.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:03.7.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:03.7.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -0:03.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:02.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.9.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:01.9.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:01.9.0 editor:indent (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
php-integrator-autocomplete-plus, v0.2.1
php-integrator-tooltips, v0.2.0

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
@hahmjt I'm afraid you missed the note in the README of this package (and the tooltips package as well): you need to install the php-integrator-base package as well (and set it up correctly) for the other packages to work. The base package provides the actual service whilst all the other packages 'plug in' to that package.

Hope this helps!
