### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAvailableVariables' of null

### ISSUE THREAD

**Issue by enno87** [Gert-dev/php-integrator-autocomplete-plus#18]
[Enter steps to reproduce below:]

1. Starting Atom
2. Editing PHP File

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getAvailableVariables' of null

```
At /home/enrico/.atom/packages/php-integrator-autocomplete-plus/lib/VariableProvider.coffee:38

TypeError: Cannot read property 'getAvailableVariables' of null
    at VariableProvider.module.exports.VariableProvider.getSuggestions (/home/enrico/.atom/packages/php-integrator-autocomplete-plus/lib/VariableProvider.coffee:38:29)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
  2x -0:18.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:18 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  3x -0:07.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:02.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "git-blame"
    ]
  },
  "php-integrator-autocomplete-plus": {
    "insertNewlinesForUseStatements": true
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.1
atom-hyperlinks, v0.1.5
atomatigit, v1.5.5
autoclose-html, v0.19.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.3.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
branch-status, v0.8.1
color-picker, v2.0.13
editorconfig, v1.2.2
file-icon-supplement, v0.8.3
file-icons, v1.6.12
git-go, v1.0.1
git-log, v0.4.1
html-id-class-snippets, v1.4.1
icon-fonts, v1.8.3
js-hyperclick, v1.4.0
language-blade, v0.16.0
language-diff, v0.4.0
laravel, v0.7.0
minimap, v4.16.2
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.1
php-getters-setters, v0.5.5
php-integrator-autocomplete-plus, v0.3.0
recent-files-fuzzy-finder, v0.2.2
tag, v0.3.0
useful-context-menu, v0.3.0
vagrant, v0.1.0

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
@enno87 You do not have the php-integrator-base package installed, which is needed to run autocomplete-plus. Still, I'm leaving this open and marking it as a bug since no errors should be thrown when the service is not available.
