### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getGlobalConstants' of null

### ISSUE THREAD

**Issue by at-nguyenvq** [Gert-dev/php-integrator-autocomplete-plus#26]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Ubuntu 14.04.3
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v0.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getGlobalConstants' of null

```
At /home/nguyenvq/.atom/packages/php-integrator-autocomplete-plus/lib/ConstantProvider.coffee:27

TypeError: Cannot read property 'getGlobalConstants' of null
    at ConstantProvider.module.exports.ConstantProvider.getSuggestions (/home/nguyenvq/.atom/packages/php-integrator-autocomplete-plus/lib/ConstantProvider.coffee:27:24)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:286:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:265:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:252:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -0:46.9.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:46.9.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:46.7.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:46.7.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:46.5.0 snippets:previous-tab-stop (atom-text-editor.editor.is-focused)
     -0:46.5.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -0:45.6.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:42.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:42.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:42.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:41.3.0 atom-save-all:saveAll (atom-text-editor.editor.is-focused)
     -0:35.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:05.8.0 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:04.6.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:02.1.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.14
angularjs, v0.3.3
atom-autocomplete-php, v0.18.1
atom-beautify, v0.28.19
atom-homestead, v1.0.1
atom-save-all, v0.4.1
autocomplete-angular-material, v0.4.0
autocomplete-html-entities, v0.1.0
laravel, v0.7.0
laravel-snippets, v2.1.0
php-analyser, v0.2.0
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.1
php-integrator-autocomplete-plus, v0.3.0
sync-on-save, v0.1.4

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
Please install the base package as well (php-integrator-base), see also the readme for more information. In the next version this error will no longer be thrown (it will fail silently instead).
