### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by kadevland** [Gert-dev/php-integrator-autocomplete-plus#50]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Debian GNU/Linux
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of null

```
At /home/kaosland/.atom/packages/php-integrator-autocomplete-plus/lib/MemberProvider.coffee:95

TypeError: Cannot read property 'then' of null
    at MemberProvider.module.exports.MemberProvider.getSuggestions (/home/kaosland/.atom/packages/php-integrator-autocomplete-plus/lib/MemberProvider.coffee:95:97)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /usr/share/atom/resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```

### Commands

```
     -3:41 tabs:close-all-tabs (div.close-icon)
     -3:23.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.seti-ui-no-icons.theme-one-dark-syntax.theme-one-dark-ui)
  2x -2:55.4.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -2:52.6.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  3x -2:49.8.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:47.5.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
  2x -2:45.2.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:44.4.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -2:43.1.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
 19x -2:31.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:27.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -2:27.3.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -2:27.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:24.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:10.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide",
      "archive-view",
      "autoflow",
      "dev-live-reload",
      "exception-reporting",
      "git-diff",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-objective-c",
      "language-perl",
      "language-make",
      "language-property-list",
      "language-ruby-on-rails",
      "language-ruby",
      "language-toml",
      "markdown-preview-plus",
      "minimap-find-and-replace",
      "minimap-highlight-selected",
      "image-view",
      "language-csharp",
      "language-source",
      "atom-message-panel-service",
      "atom-uikit",
      "linter-sass-lint",
      "fuzzy-finder",
      "bookmarks",
      "styleguide",
      "vim-mode",
      "minimap-bookmarks",
      "php-extract-method",
      "metrics",
      "php-integrator-symbol-viewer",
      "atom-php-navigation",
      "php-debug",
      "php-getters-setters",
      "welcome",
      "timecop",
      "open-on-github",
      "background-tips",
      "language-todo",
      "link",
      "markdown-preview",
      "deprecation-cop",
      "autocomplete-php",
      "gulp-manager",
      "bottom-dock"
    ],
    "followSymlinks": false,
    "openEmptyEditorOnStart": false
  },
  "php-integrator-autocomplete-plus": {
    "disableBuiltinAutocompletion": false
  }
}
```

### Installed Packages

```coffee
# User
aligner-php, v1.0.0
atom-autocomplete-php, v0.18.7
autocomplete-sass, v0.1.0
color-picker, v2.1.1
css-color-underline, v1.0.1
css-snippets, v0.9.0
css-specificity, v0.2.2
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.6
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-js-yaml, v1.2.5
linter-jscs, v3.5.0
linter-jshint, v2.1.0
linter-manager, v0.2.12
linter-php, v1.2.0
linter-phpcs, v1.3.2
linter-scss-lint, v2.5.1
minimap, v4.22.1
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.5
php-composer-completion, v0.3.4
php-cs-fixer, v2.5.6
php-integrator-annotations, v0.4.0
php-integrator-autocomplete-plus, v0.7.0
php-integrator-base, v0.8.1
php-integrator-call-tips, v0.2.3
php-integrator-navigation, v0.6.2
php-integrator-refactoring, v0.4.2
php-integrator-tooltips, v0.6.0
php-twig, v4.0.0
plantuml-viewer, v0.7.0
project-manager, v2.9.7
sass-autocompile, v0.12.6

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
I haven't forgotten about this: it should be fixed in the upcoming 0.8.0 release.

**Comment by Gert-dev** [comment]
This should now be fixed, let me know if it pops up again.

**Comment by kadevland** [comment]
i haven't try since.
i tell you if pops up again
