### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of null

### ISSUE THREAD

**Issue by fearcraftor** [Gert-dev/php-integrator-autocomplete-plus#56]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 15.10
**Thrown From**: [php-integrator-autocomplete-plus](https://github.com/Gert-dev/php-integrator-autocomplete-plus) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of null

```
At /home/florent/.atom/packages/php-integrator-autocomplete-plus/lib/FunctionProvider.coffee:72

TypeError: Cannot read property 'dispose' of null
    at FunctionProvider.module.exports.FunctionProvider.deactivate (/home/florent/.atom/packages/php-integrator-autocomplete-plus/lib/FunctionProvider.coffee:72:23)
    at Object.module.exports.deactivateProviders (/home/florent/.atom/packages/php-integrator-autocomplete-plus/lib/Main.coffee:114:22)
    at Disposable.disposalAction (/home/florent/.atom/packages/php-integrator-autocomplete-plus/lib/Main.coffee:130:35)
    at Disposable.module.exports.Disposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/disposable.js:26:16)
    at /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at Provider.module.exports.Provider.destroy (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:42:39)
    at Disposable.disposalAction (/opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:36:20)
    at Disposable.module.exports.Disposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/disposable.js:26:16)
    at /opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:25:29
    at Set.forEach (native)
    at CompositeDisposable.module.exports.CompositeDisposable.dispose (/opt/atom/resources/app.asar/node_modules/event-kit/lib/composite-disposable.js:24:26)
    at Package.module.exports.Package.deactivateResources (/opt/atom/resources/app.asar/src/package.js:674:15)
    at Package.module.exports.Package.deactivate (/opt/atom/resources/app.asar/src/package.js:635:12)
    at PackageManager.module.exports.PackageManager.deactivatePackage (/opt/atom/resources/app.asar/src/package-manager.js:622:12)
    at PackageManager.module.exports.PackageManager.update (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:366:23)
    at PackageCard.module.exports.PackageCard.update (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:705:34)
    at HTMLButtonElement.<anonymous> (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:314:24)
    at HTMLButtonElement.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/opt/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "sublime-default-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v8.11.0
emmet, v2.4.3
linter, v1.11.14
php-integrator-autocomplete-plus, v1.0.0
php-integrator-base, v0.9.5
php-integrator-tooltips, v0.6.1
rails-i18n-autocomplete, v0.4.0
sublime-default-syntax, v0.2.7

# Dev
No dev packages
```

**Comment by Gert-dev** [comment]
I see you still have version 0.9.5 of the base package, from which I can deduce that you were probably in the middle of updating your packages.

Can you still reproduce this issue after having all packages updated?

**Comment by Gert-dev** [comment]
I'll assume that the author just clicked the "Report issue" button in Atom, do let me know if this continues to happen.
